# Generated by Django 3.2.24 on 2024-03-15 09:43

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_cycle', '0005_remove_run_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentcycle',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpaymentcycle',
            name='end_date',
            field=core.fields.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalpaymentcycle',
            name='start_date',
            field=core.fields.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentcycle',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentcycle',
            name='end_date',
            field=core.fields.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentcycle',
            name='start_date',
            field=core.fields.DateField(),
        ),
    ]
